# Generated by Django 5.2 on 2025-05-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_turnover', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Минимален оборот за бонус')),
                ('bonus_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума на бонуса')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна настройка')),
            ],
            options={
                'verbose_name': 'Бонус настройка',
                'verbose_name_plural': 'Бонус настройки',
            },
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='total_bonuses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общо получени бонуси'),
        ),
    ]
