# Generated by Django 5.2 on 2025-04-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_order_restaurant_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('pizza', 'Пица'), ('pasta', 'Паста'), ('salad', 'Салата'), ('dessert', 'Десерт'), ('drink', 'Напитка')], default='pizza', max_length=50),
        ),
    ]
