# Generated by Django 5.2 on 2025-04-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('pizza', 'Пица'), ('pasta', 'Паста'), ('salad', 'Салата'), ('dessert', 'Десерт'), ('drink', 'Напитка')], max_length=50),
        ),
    ]
